version: '3.8'

services:
  web:
    build:
      context: .  # Assure la construction locale
    image: my-flask-app
    container_name: flask-app
    environment:
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-admin}
      DB_NAME: ${DB_NAME:-sportConnectBack}
      DB_PORT: "5432"
      DB_HOST: db
      SECRET_KEY: ${SECRET_KEY:-default_secret}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-default_jwt_secret}
    ports:
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/sport/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - db   # Suppression de `condition` pour éviter l'erreur de compatibilité
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
      POSTGRES_DB: ${DB_NAME:-sportConnectBack}
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-sportConnectBack} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Exposé pour les tests CI
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  pgdata: